version: '3.1'
services:
  em-project:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - test-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://test-db:5432/em_main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  test-db:
    image: postgres:14-alpine
    container_name: em_db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=em_main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres